version: '3.8'

services:
  # Cấu hình cho Server Spring Boot
  fashion_app:
    build: .
    container_name: fashion_springboot_server
    ports:
      - "8081:8081" # Map cổng 8081 từ container ra ngoài máy host
    depends_on:
      - fashion_db
    environment:
      # Ghi đè cấu hình DB để kết nối sang container MySQL (thay localhost bằng tên container db)
      - SPRING_DATASOURCE_URL=jdbc:mysql://fashion_db:3306/fashion_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    restart: always

  # Cấu hình cho Database MySQL
  fashion_db:
    image: mysql:8.0
    container_name: fashion_mysql_server
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=fashion_shop
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql # Lưu trữ dữ liệu DB không bị mất khi tắt container
    restart: always

volumes:
  db_data: