server.port = 8081

# 1. Trỏ đường dẫn tới container MySQL (fashion_db)
spring.datasource.url=jdbc:mysql://fashion_db:3306/fashion_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# 2. Tài khoản và mật khẩu phải khớp với cấu hình trong file docker-compose.yml
spring.datasource.username=root
spring.datasource.password=rootpassword

# 3. Giữ nguyên cấu hình JWT chuẩn của bạn
jwt.secret=SneakPeakSuperSecretKeyForJwtAuthentication
jwt.expiration=86400000