server.port = 8081

spring.datasource.url=jdbc:mysql://localhost:3306/fashion_shop

spring.datasource.username=your_username_here
spring.datasource.password=your_password_here

jwt.secret=nhap_secret_key_cua_ban_vao_day
jwt.expiration=864000001